mkdir ~/tx2_workdir/toolchain
echo Extracting Linux for Tegra...
sudo tar xpf ~/Jetson_Linux_R32.7.3_aarch64.tbz2 -C ~/tx2_workdir
echo Extracting Sample rootfs...
sudo tar xpf ~/Tegra_Linux_Sample-Root-Filesystem_R32.7.3_aarch64.tbz2 -C ~/tx2_workdir/Linux_for_Tegra/rootfs
echo Extracting toolchain...
tar xpf ~/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz -C ~/tx2_workdir/toolchain
